### ISSUE TITLE
Failing tests when commiting

### ISSUE THREAD

**Issue by TehSebaXx** [fus-marcom/resource-center#32]
As I mentioned yesterday in the stream, I keep failing test when I try to commit (just to sync my fork with the repo).

I'm on W10 x64. Tested in Git for Windows, CMD and Powershell.

Screenshots:

![captura1](https://user-images.githubusercontent.com/21975778/29076265-52a4dfa0-7c55-11e7-82d1-708e83998366.PNG)
![captura2](https://user-images.githubusercontent.com/21975778/29076266-53b78726-7c55-11e7-8815-57ae4f542bba.PNG)

Pinging @kebien6020 since he's the one implementing the tests.

**Comment by planigan** [comment]
@TehSebaXx that pull request will allow you to configure `TEST_TIMEOUT` in `.env`.

**Comment by planigan** [comment]
@TehSebaXx I was trying to make another commit to this PR with changes @kebien6020 pointed out and got this error even with my changes to be able to set the timeout to 40000. After committing with `--no-verify` and trying to reproduce, I can't make it fail again. Try running the tests first `npm test` before committing. See if they fail that way. If they pass, try committing again and see what happens.

**Comment by TehSebaXx** [comment]
@planigan I cloned your branch and ran `yarn test` but I'm still failing... Now I'm getting some extra errors ` Error Failed: navigation error` then the Timeout error...

**Comment by TehSebaXx** [comment]
It was running... 
I just tested on Ubuntu and failed one test then I tried again twice and it passed all...
I think I messed up on Windows because I forgot to switch branches... I'll try again later because right now Ubuntu is installing updated and I don't want to shut it down.

**Comment by TehSebaXx** [comment]
Mentioning here just in case... Managed to make it work on Ubuntu but with the same setup on W10 it doesn't work.

**Comment by TehSebaXx** [comment]
Finally managed to pass all the test...
The solution is easy.
All you have to do is to set `NIGHTMARE_GOTO_TIMEOUT=40000` in the .env file (or at least this is what worked for me, play with the timeout until it works for you).
Thanks @planigan !!

**Comment by planigan** [comment]
Your welcome @TehSebaXx. You had pulled from my repo, correct?

**Comment by TehSebaXx** [comment]
@planigan at first I did, but now I just changed `NIGHTMARE_GOTO_TIMEOUT` to 40000 on my fork. For some reason on Ubuntu your fork worked fine a few times but then started to fail again,

**Comment by planigan** [comment]
Weird. I don't know what that variable would do without my fork. Also, @kebien6020 suggested that that variable would be more helpful if it were lowered rather than raised.
