### ISSUE TITLE
Add Google Analytics tracking

### ISSUE THREAD

**Issue by cr101** [fus-marcom/resource-center#45]
You might want to add Google Analytics tracking to the web app using [autotrack](https://github.com/googleanalytics/autotrack) on `componentDidMount()`

**Comment by JesseRWeigel** [comment]
This is a great idea! Maybe we should do implement it like we did here: https://github.com/fus-marcom/ci-react/blob/master/utils/analytics.js

An also add click tracking, especially for downloads somewhat like this: https://github.com/fus-marcom/ci-react/blob/master/components/OutLink.js

**Comment by JesseRWeigel** [comment]
e7ddfed 
4ae9f7f 
f1f682f
