### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by TehSebaXx** [fus-marcom/resource-center#54]
I think that those who that are not familiar with Git and want to start using it, they should have a small tutorial on how to install git.

For Linux users the terminal command should be added.
For Mac users I guess it's the same as for Linux.
For Windows users I use [Git for Windows](https://git-scm.com/).

And if someone can link or write a small tutorial or other resources for newbies on how to use git (basics) that would be awesome.

**Comment by JesseRWeigel** [comment]
This is a great idea @TehSebaXx !

I will do a short (hopefully) video on Git and Github sometime in the near future. Just the basics.

Also, there is a series of videos on the FCC youtube channel that goes over Git as well.

**Comment by TehSebaXx** [comment]
Found the FCC Git playlist: https://www.youtube.com/watch?v=vR-y_2zWrIE&list=PLWKjhJtqVAbkFiqHnNaxpOPhh9tSWMXIF

**Comment by kukiron** [comment]
Added tutorial links with this [PR](https://github.com/fus-marcom/resource-center/pull/57).

Maybe Jesse should do a video series as well on Git for beginners.

**Comment by TehSebaXx** [comment]
Also add the [git docs](https://git-scm.com/) and this [free Udacity Course for git](https://www.udacity.com/course/how-to-use-git-and-github--ud775#) and I think this will be enough.

**Comment by TehSebaXx** [comment]
I also found this gist on reddit that might be useful to everybody https://gist.github.com/eashish93/3eca6a90fef1ea6e586b7ec211ff72a5

**Comment by JesseRWeigel** [comment]
#58 Thanks @TehSebaXx  and @kukiron !
